### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by adrian7** [wattsjus/plinq#2]
1) IMO it would be a good idea to add namespaces to the classes;
2) PHPDoc for classes and functions would be really helpful.

Also I'm wondering if this could integrate with an orm, but just a thought at this time.

Great code otherwise :)

**Comment by wattsjus** [comment]
Great suggestion, yes, I'm going to add in namespaces in the future.

**Comment by wattsjus** [comment]
In the future it's planned to allow orm integrations, it's planned to have the statements be agnostic to the data source, even have custom integrations, for now it's just mysqli and each statement can only connect to one source.  If you are able or willing I could use some input on how you may accomplish this feature.
